apiVersion: apps/v1
kind: Deployment
metadata:
  name: encuestapp
  labels:
    app: encuestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encuestapp
  template:
    metadata:
      labels:
        app: encuestapp
    spec:
      containers:
        - name: encuestapp
          image: 192.168.49.1/encuestapp-prueba/encuestapp:dev-2eba3d0
          ports:
            - containerPort: 80
