apiVersion: apps/v1
kind: Deployment
metadata:
  name: encuestapp
  labels:
    app: encuestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encuestapp
  template:
    metadata:
      labels:
        app: encuestapp
    spec:
      containers:
        - name: encuestapp
          image: 100.121.129.111:82/encuestapp-prueba/encuestapp:ec8c28d
          ports:
            - containerPort: 80
